### ISSUE TITLE
Formatting script doesn't exist

### ISSUE THREAD

**Issue by orta** [actions/javascript-template#10]
Can't run npm run format from the README - given the set of packages I couldn't make the assumption on what you were planning, so opted for an issue.

**Comment by damccorm** [comment]
Yeah, we cut code formatting from this repo as it feels more like a dev specific choice (I definitely personally still recommend adding formatting with [Prettier](https://github.com/prettier/prettier), but that's personal preference 😃).

I cut that step from the walkthrough

**Comment by damccorm** [comment]
I'm going to close here since I think that takes care of the issue - if I'm wrong comment and we can reopen!
