### ISSUE TITLE
core.debug does not seem to produce any visible output

### ISSUE THREAD

**Issue by JJ** [actions/javascript-template#17]
This line
https://github.com/actions/javascript-template/blob/master/src/main.ts#L6

does not really seem to produce any output. As a matter of fact, it's substituted by `console.log` in the walkthrough. Is there any way to see those logs (raw logs didn't show that either), or is it better to change it to console.log?

**Comment by damccorm** [comment]
They're different concepts, that is debug output. See https://github.com/actions/toolkit/blob/master/docs/action-debugging.md

**Comment by JJ** [comment]
So maybe mention that in the documentation? Or link that page from the README.md?

**Comment by garronej** [comment]
Even better would be to add it in the jsdoc of ``@action/core``  for the method ``.debug()``
